### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by yuwex** [Looky1173/Scratch-Auth-Client#1]
Hey! I found a vulnerability and I don't want to expose it here. Is there any way we can chat off site?

**Comment by Looky1173** [comment]
Yes, just send me an email to looky1173 [at] gmail [dot] com

**Comment by Looky1173** [comment]
Resolved by Looky1173/Scratch-Auth-Server@1808476689dd30533cbc9777afd1ef817ee5d2ac.
