### ISSUE TITLE
Cannot log in while banned

### ISSUE THREAD

**Issue by LucaBuca17** [Looky1173/Scratch-Auth-Client#11]
I can't log in because I'm banned

**Comment by Looky1173** [comment]
Sorry, there's no way around that. The purpose of Scratch Auth is to provide websites with a way to associate you with your Scratch account; if you are banned, you no longer have access to your Scratch account, so it's not possible for Scratch Auth to verify your identity on Scratch.

**Comment by LucaBuca17** [comment]
Hello Looky1173. couldn't you let the scratchers make a pin while signing in?

**Comment by Looky1173** [comment]
I don't understand, what do you mean by "make a pin while signing in"?

**Comment by LucaBuca17** [comment]
you will add an urgent textbox (number) for 4-8 digits and also add a PERNAMENT login for a user (me) who had a login with NotesHere and was banned and lost his WHOLE account on penguinmod. now he WON'T log out of penguinmod with his account LucaBuca17.

**Comment by Looky1173** [comment]
I can't do that; how would I guarantee that it is indeed you who would be using such a "permanent login" feature?
