### ISSUE TITLE
Reenable Cloud Auth

### ISSUE THREAD

**Issue by Steve0Greatness** [Looky1173/Scratch-Auth-Client#12]
Cloud monitor seems to have come back online, as seen on [*Cloud Platformer Multiplayer Fun v1.42*'s cloud monitor](https://scratch.mit.edu/cloudmonitor/12785898).

**Comment by Looky1173** [comment]
Thanks for letting me know, I will re-enable cloud auth once I get the associated Scratch project back up. In the meantime, I've disabled both cloud and project comment auth.

**Comment by Looky1173** [comment]
Resolved (#12).
