### ISSUE TITLE
Authentication Project has been removed

### ISSUE THREAD

**Issue by Steve0Greatness** [Looky1173/Scratch-Auth-Client#13]
Hey @Looky1173! It seems like the Authentication project has been removed the by ST(or maybe you unshared it?). Do you possibly know more about this?

I'm assuming that it was taken down for the same reason as last time, but I'm not 100% sure.

**Comment by Looky1173** [comment]
> "Help keep the site friendly" - The Scratch Team has removed this project because it is inappropriate for the Scratch website. Scratch is for kids ages 8 and up, and some subjects are too intense for a service used by young children. Please ensure your project text, labels, images, audio, lyrics, and notes are friendly and appropriate for all ages. Please follow the [Community Guidelines](https://scratch.mit.edu/community_guidelines) when using Scratch.

Ridiculous.

Reaching out to the ST is useless, so I guess I will just duplicate the project a bit later. Thanks for letting me know that it was taken down.

**Comment by Steve0Greatness** [comment]
> Reaching out to the ST is useless, so I guess I will just duplicate the project a bit later. Thanks for letting me know that it was taken down.

Yeah, no problem.

**Comment by Looky1173** [comment]
Resolved (#12).
