### ISSUE TITLE
[bug] Case sensitive usernames

### ISSUE THREAD

**Issue by Steve0Greatness** [Looky1173/Scratch-Auth-Client#15]
Scratch Auth handles usernames case sensitively, when they are really case insensitive. This has resulted in some users not being able to authenticate as they're not typing in their usernames like they did when they signed up for Scratch.

This can be fixed with the [`String.prototype.toLowerCase()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase) method.

**Comment by Steve0Greatness** [comment]
@Looky1173, could you take a look at this?

**Comment by Looky1173** [comment]
Fixed in Looky1173/Scratch-Auth-Server@43893ce9f9dfce0c0cd4def4062ebc7c2e8c41f6 and Looky1173/Scratch-Auth-Server@6bc7b41d71e168a0a989a6b7edf7409661cc7d9d.
