### ISSUE TITLE
Profile comments not working at all

### ISSUE THREAD

**Issue by tallypaws** [Looky1173/Scratch-Auth-Client#17]
I don't know the cause of this, just opening an issue to see what the issue is.
And yes I copied the code and didnt type it

**Comment by Looky1173** [comment]
Profile comments _are_ working for me. Up until now Scratch Auth was case-sensitive, so perhaps you didn't type your username exactly as it's on Scratch, but I've just made the process case-insensitive (see #15). Please try again and let me know how it goes.

**Comment by NotCryptid** [comment]
haii im having the same issue and idk what to do :P
