### ISSUE TITLE
Error when Running Locally -- iron-session: Bad usage.

### ISSUE THREAD

**Issue by Steve0Greatness** [Looky1173/Scratch-Auth-Client#18]
Hey Looky! Not sure if you're having this error, but when I run this repository locally.

> # Server Error
> 
> **Error: iron-session: Bad usage. Minimum usage is const session = await getIronSession(req, res, { cookieName: "...", password: "...". Check the usage here: https://github.com/vvo/iron-session**
> This error happened while generating the page. Any console logs will be displayed in the terminal window.
> ## Call Stack
> **getIronSession**
>    file:/C:/Users/▇▇▇▇/Documents/Scratch-Auth-Client/node_modules/iron-session/dist/index.mjs (19:11)
>
> **nextApiHandlerWrappedWithIronSession*
>    (api)\node_modules\iron-session\next\dist\index.mjs (35:40)
>
> **Object.apiResolver**
>    file:/C:/Users/▇▇▇▇/Documents/Scratch-Auth-Client/node_modules/next/dist/server/api-utils/node.js (184:15)
> **process.processTicksAndRejections**
>    node:internal/process/task_queues (95:5)
>
> **async DevServer.runApi**
>    file:/C:/Users/▇▇▇▇/Documents/Scratch-Auth-Client/node_modules/next/dist/server/next-server.js (397:9)
>
> **async Object.fn**
>    file:/C:/Users/▇▇▇▇/Documents/Scratch-Auth-Client/node_modules/next/dist/server/base-server.js (473:37)
>
> **async Router.execute**
>    file:/C:/Users/▇▇▇▇/Documents/Scratch-Auth-Client/node_modules/next/dist/server/router.js (233:32)
>
> **async DevServer.run**
>    file:/C:/Users/▇▇▇▇/Documents/Scratch-Auth-Client/node_modules/next/dist/server/base-server.js (583:29)
>
> **async DevServer.run**
>    file:/C:/Users/▇▇▇▇/Documents/Scratch-Auth-Client/node_modules/next/dist/server/dev/next-dev-server.js (445:20)
>
> **async DevServer.handleRequest**
>    file:/C:/Users/▇▇▇▇/Documents/Scratch-Auth-Client/node_modules/next/dist/server/base-server.js (298:20)

This happens for both `npm run dev` and `yarn dev`.

**Comment by Looky1173** [comment]
Hi, you need to set an ecryption password for [`iron-session`](https://github.com/vvo/iron-session). Make sure to have a local env variable `.env.local` like this:
```env
SERVER_URL=http://localhost:8080
SECRET_COOKIE_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

The password needs to be at least 32 characters long.

**Comment by Steve0Greatness** [comment]
Thanks for your help!
