### ISSUE TITLE
Wrong PenguinMod link in docs

### ISSUE THREAD

**Issue by yoyomonem** [Looky1173/Scratch-Auth-Client#19]
In the documentation, the wrong link for PenguinMod is used. PenguinMod has moved to [penguinmod.com](https://penguinmod.com), so basically what you should do is use [penguinmod.com](https://penguinmod.com) instead of [penguinmod.site](https://penguinmod.site), since [penguinmod.site](https://penguinmod.site)'s use has ended.

**Comment by Looky1173** [comment]
Fixed in b920366.
