### ISSUE TITLE
want to translate

### ISSUE THREAD

**Issue by ghost** [Looky1173/Scratch-Auth-Client#2]
I am very interested in this system.
Would you please consider translating it so that it can be used by more people?
I wish I could change the translation file with a pull request from the Transifex or GitHub.

If the translation function is implemented, 
I will help translate it into Japanese.

**Comment by Looky1173** [comment]
@tsumuri1017 That's a great idea! Currently, the website is hardcoded to be in English, but I could look into adding dynamic language switching. I will keep you updated here.

**Comment by ghost** [comment]
Thank you very much!

**Comment by Looky1173** [comment]
Closing for now due to inactivity as well as because the person who raised the issue and volunteered to translate had deleted their GitHub account.
