### ISSUE TITLE
Renable cloud and project comment auth

### ISSUE THREAD

**Issue by Steve0Greatness** [Looky1173/Scratch-Auth-Client#20]
I declare victory.

![Uploading Screenshot_20240328-125556.png …]()

**Comment by Steve0Greatness** [comment]
Oh dang. The image didn't upload.

Here is the image through Cube upload: https://u.cubeupload.com/Steve_Greatness/Screenshot2024032812.png

Dang, CubeUpload is offline as well.

Basically: it was a screenshot of an email I received that said that ST had reinstated all 3 auth projects.

**Comment by Looky1173** [comment]
Hooray! Thank you so much for "fighting" this out! :D

I've reinstated cloud and comment auth in c5d22eab92302eb3de4b0b6f639c4ad1dd2f29ab.
