### ISSUE TITLE
Remove the "New" tag for profile comments and change "Comments" to "Project comments"

### ISSUE THREAD

**Issue by Adzboy** [Looky1173/Scratch-Auth-Client#3]
I'm not sure if this is the right repo but I would like to suggest changes to the [Auth page.](https://auth.itinerary.eu.org/auth)

The first thing I would like to suggest is removing the tag in the top right of the "Profile Comments" option as it isn't a new option anymore.

The second thing is changing the "Comments" verification option to "Project Comments" for better clarification.

Thanks! 😃

**Comment by Looky1173** [comment]
Thanks for the suggestions, implemented in 80dabb79fc59111735f7b588186bd5544b0e46c9.

**Comment by Adzboy** [comment]
> Thanks for the suggestions, implemented in [80dabb7](https://github.com/Looky1173/Scratch-Auth-Client/commit/80dabb79fc59111735f7b588186bd5544b0e46c9).

Awesome!
