### ISSUE TITLE
Alternative sign-in method

### ISSUE THREAD

**Issue by PPPDUD** [Looky1173/Scratch-Auth-Client#5]
I was just about to renew my One-Click Sign-In account, but it already expired, and now I can't log in since I'm banned. Would you please add an alternative login system?

Edit: wrong repo, sorry
Edit 2: I would still love if you added that feature either way - reopening

**Comment by PPPDUD** [comment]
> What kind of alternative login system?

A way to use Github instead of Scratch for logging in.

**Comment by Adzboy** [comment]
> > What kind of alternative login system?
> 
> A way to use Github instead of Scratch for logging in.

How would that work? This is meant to be a system for Scratch logins, not logging in with GitHub as you can't use ScratchDB to find out data about the account

**Comment by PPPDUD** [comment]
I was thinking that it would be a mirror of the existing login system for
Github, but it would work with websites that already use Scratch Auth.

**Comment by Looky1173** [comment]
Sorry, but Scratch Auth is meant to provide Scratch related websites with Scratch usernames to let people authenticate -- you can't link a GitHub account to Scratch. Also, if you are banned on Scratch, I don't see what use Scratch related websites could be for you.

**Comment by PPPDUD** [comment]
I can make (somewhat useless) profit from children online using Shinies,
and I can find the latest ATs buzz while being IP banned with Ocular.

**Comment by PPPDUD** [comment]
But I can't share fun facts through Ocular if I'm not logged in.

**Comment by Looky1173** [comment]
You have all the Ocular fun facts [here](https://github.com/jeffalo/ocular/blob/37948535e46e9808e349dda8a8faaffb27934d80/components/Loading.vue#L12-L69).

**Comment by PPPDUD** [comment]
I mean changing my Ocular status so I can tell my own fun facts.

**Comment by Looky1173** [comment]
I understand, but what's the point of Ocular statuses if you're banned on Scratch?

**Comment by PPPDUD** [comment]
People with Screeching Avocados will see the status with all of my posts.

**Comment by PPPDUD** [comment]
Scratch A**ons.
