### ISSUE TITLE
Documenation Request: Custom Frontends

### ISSUE THREAD

**Issue by Steve0Greatness** [Looky1173/Scratch-Auth-Client#7]
I think it's important to have this information, as it's pretty difficult to find otherwise. Like, I know that it's the last post of page 15 on the Itinerary topic, but not everybody does.

![I could add some more customisation options but it would be impossible to provide enough parameters to accommodate to everyone's needs. If you want an entirely custom authentication page, build it yourself and use the backend API directly (auth-api.itinerary.eu.org). | • GET auth-api itinerary.eu.org/auth/getTokens | Query options: | redirect - String (Base64 encoded URL with or without "https://" prefix) | method - Enum ("cloud", "comment") | • GET auth-api.itinerary.eu.org/auth/verifyToken/:privateCode | Query parameters: | privateCode* -String | Query options: | redirect - String (Base64 encoded URL with or without "https://" prefix, only required when the oneClickSignin query option is true) oneClickSignIn-Boolean | GET auth-api.itinerary.eu.org/auth/oneClickSignin | Headers: | Authorization-String | • POST auth-api.itinerary.eu.org/auth/oneClickSignIn/:username | Headers: | Authorization - String | Query parameters: | username* -String | Query options: | redirect - String (Base64 encoded URL with or without "https://" prefix) | • DELETE auth-api.itinerary.eu.org/auth/oneClickSignIn/:username | Headers: | Authorization" - String | Query parameters: | username - String | * = required | Should you have any questions about the backend API, please ask here. I might add the endpoints to the documentation too. | Also, I'm open to minor customisation suggestions but no colour changes please (for mostly technical reasons).](https://github.com/Looky1173/Scratch-Auth-Client/assets/75220768/722bb72d-7f54-445c-bf7b-f28e3cf5c6fb)

**Comment by Looky1173** [comment]
This is another long overdue issue; thank you for raising it. It's resolved in 8e1fe547785c2ee5eaea137203509567f5701990, and [here](https://auth.itinerary.eu.org/documentation/custom-frontend) is the new page in the documentation about custom frontends for Scratch Auth.
