### ISSUE TITLE
Redirects do not work well with query strings.

### ISSUE THREAD

**Issue by Steve0Greatness** [Looky1173/Scratch-Auth-Client#8]
Created on Behalf of [JeremyGamer13](https://scratch.mit.edu/users/JeremyGamer13); [Original comment](https://scratch.mit.edu/users/Looky1173/#comments-284757889).

An example where this bug takes affect is when you have a redirect to `example.com/?SiteTheme=purple`, due to how Scratch Auth redirects the user, rather than adding an `&`, it will instead add another `?`, resulting in `example.com/?SiteTheme=purple?privateCode=...`. I believe this could be solved by checking if the redirect url includes a `?`, and if it does, replacing the `?` in `?privateCode=...` with an `&`.

**Comment by Looky1173** [comment]
Thanks for raising this issue; fixed in 87b465d5c997596fbe63e7d0adeee74a6c3d8ff8.
